
USE Signlator;

#INSERTAR EN LA TABLA PASES
INSERT INTO Signlator.paises(nombre)
values ('Peru'),
       ('Argentina'),
       ('Brazil'),
       ('Chile'),
       ('Ecuador'),
       ('Colombia'),
       ('España'),
       ('Uruguay'),
       ('Bolivia'),
       ('Costa Rica'),
       ('Paraguay'),
       ('Venezuela'),
       ('Mexico'),
       ('El Salvador');

#INSERTAR EN LA TABLA CIUDADES
INSERT INTO Signlator.ciudades(nombre, paises_id)
values
    #PERU - ID 1
    ('Lima', 1),
    ('Callao', 1),
    ('Cusco', 1),
    ('Arequipa', 1),
    ('Trujillo', 1),
    ('Iquitos', 1),
    ('Chiclayo', 1),
    ('Huaraz', 1),
    ('Ayacucho', 1),
    ('Piura', 1),
    ('Puno', 1),
    ('Huancayo', 1),
    ('Cajamarca', 1),
    ('Tacna', 1),
    ('Juliaca', 1),
    ('Tacna', 1),
    ('Huacho', 1),
    ('Chimbote', 1),
    ('Huánuco', 1),
    ('Callao', 1),
    ('Puerto Maldonado', 1),
    ('Sullana', 1),
    ('Tarapoto', 1),
    ('Pisco', 1),
    ('Chincha Alta', 1),
    ('San Ignacio', 1),
    ('Chachapoyas', 1),
    ('Pucallpa', 1),
    ('Tumbes', 1),
    #ARGENTINA - ID 2
    ('Buenos Aires', 2),
    ('Ciudad de Santa fe', 2),
    ('Salta', 2),
    ('Ciudad de Córdoba', 2),
    ('Rosario', 2),
    ('San Miguel de Tucumán', 2),
    ('La Plata', 2),
    ('Mar de Plata', 2),
    ('Mendoza', 2),
    ('Ciudad de Santiago del Estero', 2),
    ('Resistencia', 2),
    ('Ciudad de Corrientes', 2),
    #BRAZIL - ID 3
    ('Sao Paulo', 3),
    ('Rio de Janeiro', 3),
    ('Salvador de Bahía', 3),
    ('Belo Horizonte', 3),
    ('Manaos', 3),
    ('Recife', 3),
    ('Fortaleza', 3),
    ('Porto Alegre', 3),
    ('Belén', 3),
    ('Curitiba', 3),
    ('Florianópolis', 3),
    #CHILE - ID 4
    ('Santiago de Chile', 4),
    ('Antofagasta', 4),
    ('Punta Arenas', 4),
    ('Iquique', 4),
    ('Coyhaique', 4),
    ('Arica', 4),
    ('Calama', 4),
    ('Validiva', 4),
    ('Talca', 4),
    ('Puerto Varas', 4),
    ('Copiapó', 4),
    ('Viña del Mar', 4),
    ('Valparaiso', 4),
    #ECUADOR - ID 5
    ('Quito', 5),
    ('Guayaquil', 5),
    ('Ambato', 5),
    ('Manta', 5),
    ('Machala', 5),
    ('Ibarra', 5),
    ('Loja', 5),
    ('Esmeraldas', 5),
    ('Latacunga', 5),
    ('Santo Domingo', 5),
    ('Porto Viejo', 5),
    #COLOMBIA - ID 6
    ('Bogota', 6),
    ('Medellín', 6),
    ('Cali', 6),
    ('Barranquilla', 6),
    ('Cartagena', 6),
    ('Cúcuta', 6),
    ('Bucamaramanga', 6),
    ('Ibagué', 6),
    ('Pereira', 6),
    #ESPAÑA - ID 7
    ('Madrid', 7),
    ('Barcelona', 7),
    ('Sevilla', 7),
    ('Valencia', 7),
    ('Toledo', 7),
    ('Granada', 7),
    ('Córdoba', 7),
    ('Málaga', 7),
    ('Santiago de Compostela', 7),
    ('Salamanca', 7),
    ('Zaragoza', 7),
    #URUGUAY - ID 8
    ('Montevideo', 8),
    ('Paysandú', 8),
    ('Mercedes', 8),
    ('Melo', 8),
    ('Fray Bentos', 8),
    ('Rivera', 8),
    ('San José', 8),
    ('Colonia del Sacramento', 8),
    ('Rocha', 8),
    #Bolivia - ID 9
    ('La Paz', 9),
    ('Santa Cruza de la Sierra', 9),
    ('Sucre', 9),
    ('Cochabamba', 9),
    ('El Alto', 9),
    ('Villa Imperial de Potosí', 9),
    ('Oruro', 9),
    ('Trinidad', 9),
    ('Tarija', 9),
    #Costa Rica - ID 10
    ('San José', 10),
    ('Limón', 10),
    ('Cartago', 10),
    ('Liberia', 10),
    ('Alajuela', 10),
    ('Puntarenas', 10),
    ('Heredia', 10),
    ('Sarchí', 10),
    #Paraguay - ID 11
    ('Asunción', 11),
    ('Ciudad del Este', 11),
    ('Encarnación', 11),
    ('Gran Asunción', 11),
    ('Luque', 11),
    ('Fernando de la Mora', 11),
    ('Capiatá', 11),
    #Venezuela - ID 12
    ('Caracas', 12),
    ('Marcaibo', 12),
    ('Ciudad Bolívar', 12),
    ('Valencia', 12),
    ('Barquisimeto', 12),
    ('Mérida', 12),
    ('Ciudad Guayana', 12),
    ('San Cristóbal', 12),
    #Mexico - ID 13
    ('Ciudad de México', 13),
    ('Oaxaca de Juárez', 13),
    ('Guadalajara', 13),
    ('Monterrey', 13),
    ('Ciudad de Juárez', 13),
    ('Santiago de Querétaro', 13),
    ('Cuernavaca', 13),
    ('Cancún', 13),
    #El Salvador - ID 14
    ('San Salvador', 14),
    ('Santa Ana', 14),
    ('San Miguel', 14),
    ('Sonsonate', 14),
    ('Ahuachapán', 14),
    ('La Unión', 14);

#INSERTAR EN TABLA DISTRITOS
INSERT INTO Signlator.distritos(nombre, ciudades_id)
VALUES
#LIMA - ID 1
('Lima', 1),
('San Juan de Lurigancho', 1),
('San Martín de Porres', 1),
('Ate', 1),
('Comas', 1),
('Villa el Salvador', 1),
('Villa Maria del Triunfo', 1),
('San Juan de Miraflores', 1),
('Los Olivos', 1),
('Puente Piedra', 1),
('Santiago de Surco', 1),
('Chorrillos', 1),
('Carabayllo', 1),
('Santa Anita', 1),
('Lurigancho', 1),
('Independencia', 1),
('El Agustino', 1),
('La Victoria', 1),
('La Molina', 1),
('Rimac', 1),
('San Miguel', 1),
('San Isidro', 1),
#Callao - ID 2
('Municipalidad Provincial del Callao', 2),
('Bellavista', 2),
('Carmen de la Legua', 2),
('La Punta', 2),
('La Perla', 2),
('Ventanilla', 2),
#CUSCO - ID 3
('Cusco', 3),
('Ccorca', 3),
('Poroy', 3),
('San Jerónimo', 3),
('San Sebastián', 3),
('Santiago', 3),
('Saylla', 3),
('Wanchaq', 3),
#Arequipa - ID 4
('Alto Selva Alegre', 4),
('Arequipa', 4),
('Cayma', 4),
('Cerro Colorado', 4),
('Characato', 4),
('Chiguata', 4),
('Jacobo Hunter', 4),
('José Luis Bustamante y Rivero', 4),
#Trujillo - ID 5
('Trujillo', 5),
('El Porvenir', 5),
('Florencia de Mora', 5),
('Huanchaco', 5),
('La Esperanza', 5),
('Laredo', 5),
('Moche', 5),
#Iquitos - ID 6
('Iquitos', 6),
('Belen', 6),
('Punchana', 6),
('San Juan Bautista', 6),
#Chiclayo - ID 7
('Cayaltí', 7),
('Chiclayo', 7),
('Chongoyape', 7),
('Eten', 7),
('José Leonardo Ortiz', 7),
('Lagunas', 7),
#Huaraz - ID 8
('Cochabamba', 8),
('Pira', 8),
('Independencia', 8),
('Huaraz', 8),
('Huanchay', 8),
('Pampas Grandes', 8),
('Olleros', 8),
#Ayacucho - ID 9
('Lucanas', 9),
('La Mar', 9),
('Cangallo', 9),
('Huamanga', 9),
('Lucanas', 9),
#Piura - ID 10
('Piura', 10),
('Castilla', 10),
('Catacaos', 10),
('Tambogrande', 10),
('Las Lomas', 10),
#Puno - ID 11
('Mañazo', 11),
('Vilque', 11),
('Tiquillaca', 11),
('Puno', 11),
('Ácora', 11),
#Huancayo - ID 12
('Colca', 12),
('Chongos Alto', 12),
('Huancayo', 12),
('Pariahuanca', 12),
('Santo Domingo de Acobamba', 12),
#Cajamarca - ID 13
('Cajamarca', 13),
('La Encañada', 13),
('Magdalena', 13),
('San Juan', 13),
('Los Baños del Inca', 13),
#Tacna - ID 14
('Tacna', 14),
('Palca', 14),
('Pachía', 14),
('Ciudad Nueva', 14),
('Alto de la Alianza', 14),
#Juliaca - ID 15
('Juliaca', 15),
('Caracoto', 15),
('San Roman', 15),
('Cabanillas', 15),
('Cabana', 15),
#Huacho - ID 17
('Huacho', 17),
('Sayan', 17),
('Huarua', 17),
('Leoncio Prado', 17),
('Santa María', 17),
#Chimbote - ID 18
('Chimbote', 18),
('Nuevo Chimbote', 18),
('Moro', 18),
('Caceres del Perú', 18),
('Samanco', 18),
#Huánuco - ID 19
('Chinchao', 19),
('Huánuco', 19),
('Quisqui', 19),
('Yacus', 19),
('Margos', 19),
#Puerto Maldonado - ID 21
('Tambopata', 21),
('Inambari', 21),
('Laberinto', 21),
('Las Piedras', 21),
#Sullana - ID 22
('Bellavista', 22),
('Ignacio Escudero', 22),
('Lancones', 22),
#Tarapoto - ID 23
('Tarapoto', 23),
('La Banda de Shilcayo', 23),
('Morales', 23),
('Cacatachi', 23),
#Pisco - ID 24
('Pisco', 24),
('Paracas', 24),
('Tupac Amaru', 24),
#Chincha Alta - ID 25
('El Carmen', 25),
('Alto Larán', 25),
#San Ignacio - ID 26
('Chirinos', 26),
('Tabacones', 26),
#Chachapoyas - ID 27
('Sonche', 27),
('Soloco', 27),
('Chachapoyas', 27),
('Cheto', 27),
#Pucallpa - ID 28
('Pucallpa', 28),
#Tumbes - ID 29
('Tumbes', 29),
('Corrales', 29),
('La Cruz', 29),
#Buenos Aires - ID 30
('Ituzaingó', 30),
('La Matanza', 30),
('La Plata', 30),
('Lanús', 30),
('Las Heras', 30),
#Ciudad de Santa fe - ID 31
('Arminda', 31),
('Coronel Arnold', 31),
('Funes', 31),
('Ibarlucea', 31),
#Salta - ID 32
('Rivadia', 32),
('Salta', 32),
('Oran', 32),
('La Viña', 32),
#Ciudad de Córdoba - ID 33
('Guadalquivir', 33),
('El arenal', 33),
('Cerro Muriano', 33),
#Rosario - ID 34
('Luis Agote', 34),
('Republica de la Sexta', 34),
('Alberto Olmedo', 34),
#San Miguel de Tucumán - ID 35
('Tucumán', 35),
#La Plata- ID 36
('La plata', 36),
('Abasto', 36),
('Romero', 36),
#Mar de Plata- ID 37
('Mar del Plata', 37),
#Mendoza- ID 38
('Godoy Cruz', 38),
('Gobernador Benegas', 38),
('San Francisco del Monte', 38),
#Ciudad de Santiago del Estero - ID 39
('Ibarra', 39),
('San Martín', 39),
('Silípica', 39),
('Loreto', 39),
#Resistencia - ID 40
('Resistencia', 40),
('Sé', 42),
('Bela Vista', 42),
('Provincia de Antofagasta', 54),
('Punta arenas', 55),
('Barranquilla', 80),
('Portuario', 80);



INSERT INTO Signlator.segmentos(descripcion)
VALUES ('Persona con discapacidad auditiva y del habla'),
       ('Persona cercana a persona con discapacidad auditiva'),
       ('Persona interesada en aprender lenguaje de señas');


INSERT INTO Signlator.parentescos(nombre, descripcion)
VALUES ('Padre', 'Relación parental entre el apoderado y el usuario'),
       ('Madre', 'Relación parental entre el apoderado y el usuario'),
       ('Hermano', 'Relación de hermandad entre el apoderado y el usuario'),
       ('Hermana', 'Relación de hermandad entre el apoderado y el usuario'),
       ('Tio', 'Relación de tio entre el apoderado y el usuario'),
       ('Tia', 'Relación de tia entre el apoderado y el usuario'),
       ('Abuelo', 'Relacion de abuelo entre el apoderado y el usuario'),
       ('Abuela', 'Relacion de abuela enttre el apoderado y el usuario');

INSERT INTO Signlator.apoderados(nombre, apellido, parentescos_id)
VALUES ('Juan', 'Soto', 1),
       ('Luis', 'Suarez', 3),
       ('Emilda', 'Barboza', 2),
       ('Renato', 'Victoria', 5),
       ('Dante', 'Lopez', 3),
       ('Pedro', 'Luccio', 5),
       ('Fredd', 'Sanchez', 7),
       ('Ericka', 'Alejo', 4),
       ('Ariana', 'Diaz', 8),
       ('Araceli', 'Delinda', 4),
       ('Alexander', 'Pomalaza', 5),
       ('Junior', 'Centeno', 7),
       ('Raul', 'Huaytalla', 1),
       ('Anthony', 'Carcamo', 1),
       ('Lorena', 'Balcazar', 2),
       ('Luis', 'Peves', 3),
       ('Delinda', 'Rioja', 4),
       ('Mininsor', 'Cuy', 5),
       ('Jhoel', 'Soto', 5),
       ('Eder', 'Barboza', 7),
       ('Gabriela', 'Espinoza', 8),
       ('Juancito', 'Caceres', 1);

INSERT INTO Signlator.usuarios(nombre, apellido, sexo, correo, telefono, dni, apoderados_id, segmentos_id, distritos_id)
VALUES ('Pedro', 'Soto', 'Masculino', 'pedrosotobarboza@hotmail.com', 955004465, '74920219', 3, 3, 181),
       ('Mark', 'Luciano', 'Masculino', 'markv_221@hotmail.com', 955562445, '74956259', 1, 1, 2),
       ('Luis', 'Krisch', 'Masculino', 'luizDC_f2@gmail.com', 953204464, '84920319', null, 2, 2),
       ('Giovana', 'Santander', 'Femenino', 'pedrosotobarboza@hotmail.com', 955005575, '45920219', 4, 2, 2),
       ('Resich', 'Mouilk', 'Masculino', 'resich_22_1@hotmail.com', 963852741, '32520219', null, 3, 2),
       ('Ash', 'Ketchup', 'Masculino', 'ash_del_pueblo_paleta@hotmail.com', 987654321, '85920219', 6, 2, 147),
       ('Tony', 'Stark', 'Masculino', 'elmascapito_21_3@hotmail.com', 955004213, '98720219', 7, 1, 142),
       ('Steven', 'Rogers', 'Masculino', 'vivaamerica@yahoo.com', 955126456, '15920456', 8, 3, 2),
       ('Mark', 'Ruffalo', 'Masculino', 'MarkcitoelHulk@gmail.com', 988776655, '14520219', 8, 2, 172),
       ('Reed', 'Richards', 'Masculino', 'R4@busterfoundation.com', 944004465, '84625219', 10, 1, 168),
       ('Sue', 'Storm', 'Femenino', 'S_Storm_2133@busterfoundation.com', 933004465, '45920219', null, 3, 177),
       ('Wanda', 'Maximoff', 'Femenino', 'WM_Soymala@gmail.com', 977564654, '65920219', 12, 2, 14),
       ('Mordo', 'Strange', 'Masculino', 'MStrange_2133@hotmail.com', 962224465, '74520219', 13, 1, 172),
       ('Peter', 'Parker', 'Masculino', 'PeterParker_2112@elclarín.com', 984504466, '52920281', 14, 1, 172),
       ('Mary', 'Jane', 'Femenino', 'Mary_jane_221@hotmail.com', 988332465, '15632489', 15, 1, 181),
       ('Gwen', 'Stacy', 'Femenino', 'Gwen_1222.33@hotmail.com', 975442465, '74526381', 16, 1, 181),
       ('Michelle', 'Jones', 'Femenino', 'Michelle_2_SDW@hotmail.com', 985554465, '17463254', 17, 1, 1),
       ('Pamela', 'Meza', 'Femenino', 'mezapatiñoashely@gmail.com', 997544465, '85426578', 18, 2, 179),
       ('Harry', 'Pottter', 'Masculino', 'HarryPopoter@hotmail.com', 974526465, '98745621', 19, 2, 179),
       ('Norman', 'Osborn', 'Masculino', 'elduendecittopati@gmail.com', 985442465, '54265315', 20, 2, 179);



INSERT INTO Signlator.niveles(nombre, descripcion, objetivo)
VALUES ('Señas Básico', 'Curso de lenguaje de señas a nivel básico',
        'El alumno podra aprender sobre frases básicas
        para comunicarse en lenguaje de señas'),
       ('Señas Intermedio', 'Curso de lenguaje de señas a nivel intermedio',
        'El alumno podrá aprender sobre estructura de lenguaje de señas
        para comunicarse en este medio'),
       ('Señas Avanzado', 'Curso de lenguaje de señas avanzado',
        'El alumno podrá aprender sobre los conceptos avanzados
        del lenguaje de señas');


INSERT INTO Signlator.cursos(nombre, descripcion, fecha_inicio, niveles_id)
VALUES ('Saludos en lenguaje de señas', 'Aprenderás sobre saludos',
        date_add(current_date
    , interval 50 day), 1),
       ('Despedidas en lenguaje de señas', 'Aprenderás sobre frases de despedida',
        date_add(current_date
           , interval -5 day), 1),
       ('Frases clave en lenguaje de señas', 'Aprenderás frases clave para comunicarse',
        date_add(current_date
           , interval -25 day), 1),
       ('Estructurar frases en lenguaje de señas', 'Aprenderás sobre cómo estructurar frases',
        date_add(current_date
           , interval -15 day), 2),
       ('Cómo transmitir las ideas con gestos', 'Aprenderás sobre una correcta gesticulación',
        date_add(current_date
           , interval -40 day), 2),
       ('Los movimientos y su importancia', 'Aprenderás sobre la importancia de los movimientos correctos',
        date_add(current_date
            , interval -33 day), 2),
       ('Bases para comprender una comunicación directa', 'Aprenderás sobre cómo comunicarse de forma directa',
        date_add(current_date
            , interval 12 day), 3),
       ('Fundamentos para realizar interpretación', 'Aprenderás sobre los fundamenots de interpretación',
        date_add(current_date
            , interval 5 day), 3),
       ('Bases para la enseñanza de lenguaje de señas', 'Aprenderás sobre las bases para una correcta enseñanza',
        date_add(current_date
            , interval 12 day), 3);



INSERT INTO Signlator.anuncios(titulo, descripcion)
VALUES ('Recordatorio', 'No se olviden de mantener un orden en sus cursos'),
       ('Alerta', 'Deben de finalizar sus cursos correctamente'),
       ('Recordatorio', 'Recuerden que tienen un acceso libre a cada material del curso'),
       ('Alerta', 'Deben de consultar los recursos para sus test'),
       ('Anuncio', 'Recuerden realizar sus examenes en el tiempo límite'),
       ('Anuncio', 'Recuerden que tienen acceso para cada unidad de los cursos'),
       ('Alerta', 'Se debe de consultar los recursos antes de dar sus examenes'),
       ('Anuncio', 'Se iniciarán cursos durante el siguiente mes'),
       ('Recordatorio', 'Recuerden finalizar sus cursos de forma ordenada'),
       ('Recordatorio', 'Recuerden compartir el aplicativo con sus conocidoso');

INSERT INTO Signlator.unidades(descripcion, objetivo, cursos_id)
VALUES ('Unidad 1', 'Comprender lo básico de las frases', 1),
       ('Unidad 2', 'Comprender buenos días', 1),
       ('Unidad 3', 'Comprender los saludos', 1),
       ('Unidad 1', 'Comoprender lo básico de las frases', 2),
       ('Unidad 2', 'Comprender despedidas', 2),
       ('Unidad 1', 'Comprender lo básico de las frases', 3),
       ('Unidad 2', 'Comprender cómo comunicarse de forma directa fácilmente', 3),
       ('Unidad 1', 'Comprender la estructura intermedia de las frases', 4),
       ('Unidad 2', 'Comprender cómo comunicarse a través de frases', 4),
       ('Unidad 1', 'Comprender los gestos básicos', 5),
       ('Unidad 2', 'Comprender los gestos intermedios', 5),
       ('Unidad 1', 'Comprender los movimientos', 6),
       ('Unidad 2', 'Comprender la importancia de los movimientos', 6),
       ('Unidad 1', 'Comprender la comunicación a través del lenguaje de señas', 7),
       ('Unidad 2', 'Comprender los fundamentos de la comunicación', 7),
       ('Unidad 1', 'Comprender lo principal para una correcta interpretación', 8),
       ('Unidad 2', 'Comprender cómo realizar una correcta interpretación', 8),
       ('Unidad 1', 'Comprender cómo realizar una buena enseñanza', 9),
       ('Unidad 2', 'Comprender cómo transmitir el conocimiento', 9);

INSERT INTO Signlator.temas(descripcion, unidades_id)
VALUES ('Frases básicas', 1),
       ('Buenos Días', 2),
       ('Saludos', 3),
       ('Básico de frases', 4),
       ('Despedidas', 5),
       ('Basico frases', 6),
       ('Comunicación directa', 7),
       ('Estructura de frases', 8),
       ('Comunicación a través del lenguaje de señas', 9),
       ('Gestos básicos', 10),
       ('Gestos intermedios', 11),
       ('Movimientos', 12),
       ('Importancia de Movimientos', 13),
       ('Comunicación con lenguaje de señas', 14),
       ('Fundamentos de comunicación', 15),
       ('Correcta Interpretación', 16),
       ('Bases de la interpretación', 17),
       ('Una correcta ineseñanza', 18),
       ('Transmitir conocimiento', 19);

USE Signlator;
INSERT INTO examenes (descripcion, peso, fecha_inicio, fecha_fin, temas_id)
VALUES ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 1),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 1),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 2),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 2),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 3),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 3),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 4),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 4),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 5),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 5),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 6),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 6),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 7),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 7),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 8),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 8),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 9),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 9),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 10),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 10),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 11),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 11),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 12),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 12),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 13),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 13),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 14),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 14),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 15),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 15),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 16),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 16),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 17),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 17),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 18),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 18),
       ('Examen parcial', 30, date_add(current_date, interval -8 day), date_add(current_date, interval 10 day), 19),
       ('Examen final', 70, date_add(current_date, interval 5 day), date_add(current_date, interval 20 day), 19);


INSERT INTO Signlator.archivos(descripcion, formato, duracion, enlace_archivo)
VALUES ('Archivo de texto', '.pdf', '12:30', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '10:15', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '08:30', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '11:45', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '17:50', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '12:45', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '09:50', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '13:20', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '07:45', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '10:48', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '16:12', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '15:47', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '30:24', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '25:21', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '06:30', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '09:05', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '10:14', 'http://www.lenguadeseñas.com'),
       ('Archivo de video', '.mp4', '17:25', 'http://www.lenguadeseñas.com'),
       ('Archivo de texto', '.pdf', '15:56', 'http://www.lenguadeseñas.com');

INSERT INTO Signlator.recursos(descripcion, titulo, temas_id, archivos_id)
VALUES ('Este documento permitirá comprender las frases básicas', 'Documento de frases básicas', 1, 1),
       ('Este archivo de video permitirá comprender las frases de buenos dias', 'Video de frases buenos días', 2, 2),
       ('Este documento permitirá comprender sobre saludos', 'Documento de saludos', 3, 3),
       ('Este video permitirá comprender sobre frases', 'Video de frases', 4, 4),
       ('Este documento permitirá comprender sobre despedidas', '', 5, 5),
       ('Este video permitirá aprender sobre frases', 'Video de frases básicas', 6, 6),
       ('Este documento permitirá comprender sobre la comunicación directa', 'Documento de comunicación directa', 7, 7),
       ('Este video permitira aprender sobre estructura de frases', 'Video de estructura de frases', 8, 8),
       ('Este documento permitirá aprender sobre la comunicación a través de señas',
        'Documento de comunicación en señas', 9, 9),
       ('Este video permitirá comprender sobre gestos básicos', 'Video de gestos básicos', 10, 10),
       ('Este documento permitirá aprender sobre gestos intermedios', 'Documento de gestos intermedios', 11, 11),
       ('Este video permitirá aprender sobre movimientos', 'Video de movimientos', 12, 12),
       ('Este documento permitirá aprender sobre la importancia de los movimientos',
        'Documento de la importancia de movimientos', 13, 13),
       ('Este video permitirá aprender sobre la comunicación con lenguaje de señas',
        'Video de comuniación con lenguaje de señas', 14, 14),
       ('Este documento permitirá aprender sobre fundamentos de comunicación',
        'Documento de fundamentos de comunicación', 15, 15),
       ('Este video permitirá aprender sobre la correcta interpretación', 'Video de interpretación', 16, 16),
       ('Este documento permitirá aprender sobre las bases de la interpretación', 'Documento de interpretación', 17,
        17),
       ('Este video permitirá aprender sobre una correcta enseñanza', 'Video sobre enseñanza', 18, 18),
       ('Este documento permitirá aprender sobre cómo transmitir el conocimiento',
        'Documento sobre t ransmitir conocimiento', 19, 19);


INSERT INTO Signlator.frases(descripcion, titulo)
VALUES ('Buenos días', 'Saludo mañana'),
       ('Buenas tardes', 'Saludo tarde'),
       ('Buenas noches', 'Saludo noche'),
       ('Un gusto conocerte', 'Agradecimiento'),
       ('Espero nos llevemos bien', 'Cordialidad'),
       ('Somos amigos', 'Amistad'),
       ('El clima está bonito', 'Ambiente'),
       ('Te invito a mi fiesta', 'Invitación'),
       ('Nos vemos', 'Despedida'),
       ('Hasta luego', 'Despedida'),
       ('Cómo te sientes', 'Cuestionamiento'),
       ('Te veo feliz', 'Felicidad'),
       ('Te veo animado', 'Disfrutando'),
       ('Vamos a pasear', 'Paseo'),
       ('Pensemos mucho más', 'Pensamiento'),
       ('Nos vamos juntos', 'Salida'),
       ('¿Quieres ver esto conmigo?', 'Visualizar'),
       ('Debemos hacer la tarea', 'Responsabilidad'),
       ('Tu mamá me avisó', 'Aviso'),
       ('Eso es muy peligroso', 'Peligro');


INSERT INTO Signlator.gestos(nombre, descripcion, imagen)
VALUES ('Movimiento Buenos dias', 'Movimiento que permite representar el buenos días', null),
       ('Movimiento Buenas tardes', 'Movimiento que permite representar las buenas tardes', null),
       ('Movimiento Buenos noches', 'Movimiento que permite representar el buenas noches', null),
       ('Movimiento Un gusto conocerte',
        'Movimiento que permite representar el agradecimiento de un gusto en conocerte', null),
       ('Movimiento Espero nos llevemos bien', 'Movimiento que permite representar el llevarse bien', null),
       ('Movimiento Somos amigos', 'Movimiento que permite representar el ser amigos', null),
       ('Movimiento El clima está bonito', 'Movimiento que permite representar sobre el clima', null),
       ('Movimiento Te invito', 'Movimiento que permite representar el invitar', null),
       ('Movimiento Nos vemos', 'Movimiento que permite representar el nos vemos', null),
       ('Movimiento Hasta luego', 'Movimiento que permite representar el hasta luego', null),
       ('Movimiento Como te sientes', 'Movimiento que permite representar la preocupación', null),
       ('Movimiento Te veo feliz', 'Movimiento que permite representar el te veo feliz', null),
       ('Movimiento Te veo animado', 'Movimiento que permite representar el ver animado', null),
       ('Movimiento Vamos a pasear', 'Movimiento que permite representar la invitación a pasear', null),
       ('Movimiento Pensemos', 'Movimiento que permite representar el pensar', null),
       ('Movimiento Vámonos', 'Movimiento que permite representar el irse juntos', null),
       ('Movimiento Invitar a ver', 'Movimiento que permite representar el invitar a ver algo', null),
       ('Movimiento Hacer tarea', 'Movimiento que permite representar el realizar las tareas', null),
       ('Movimiento Aviso', 'Movimiento que permite representar un aviso recibido', null),
       ('Movimiento Es muy peligroso', 'Movimiento que permite representar el peligro', null);

INSERT INTO Signlator.categorias(titulo, descripcion)
VALUES ('Saludos', 'Ideas que representan saludo'),
       ('Invitación', 'Ideas que representan invitación'),
       ('Cordialidad', 'Ideas que representan cordialidad'),
       ('Despedidas', 'Ideas que representan despedida'),
       ('Amabilidad', 'Ideas que representan amabilidad'),
       ('Avisos', 'Ideas que representan avisos'),
       ('Cultural', 'Ideas que representan culturales');


INSERT INTO Signlator.lenguajes(descripcion)
VALUES ('Español'),
       ('Lenguaje de señas');

#
INSERT INTO Signlator.ideas(descripcion, categorias_id, gestos_id, frases_id, lenguajes_id)
VALUES ('Idea en lenguaje de señas que representa los buenos días', 1, 1, 1, 2),
       ('Idea en lenguaje de señas que representa las buenas tardes', 1, 2, 2, 2),
       ('Idea en lenguaje de señas que representa las buenas noches', 1, 3, 3, 2),
       ('Idea en lenguaje de señas que representa un gusto en conocerte', 3, 4, 4, 2),
       ('Idea en lenguaje de señas que representa el espero nos llevemos bien', 3, 5, 5, 2),
       ('Idea en lenguaje de señas que representa el ser amigos', 5, 6, 6, 2),
       ('Idea en lenguaje de señas que representa que el clima está bonito', 6, 7, 7, 2),
       ('Idea en lenguaje de señas que representa el invitar', 2, 8, 8, 2),
       ('Idea en lenguaje de señas que representa la despedida de nos vemos', 4, 9, 9, 2),
       ('Idea en lenguaje de señas que representa la despedida hasta luego', 4, 10, 10, 2),
       ('Idea en lenguaje de señas que representa el preguntar cómo se siente', 5, 11, 11, 2),
       ('Idea en lenguaje de señas que representa el ver que está feliz', 5, 12, 12, 2),
       ('Idea en lenguaje de señas que representa el ver animado', 3, 13, 13, 2),
       ('Idea en lenguaje de señas que representa el invitar a pasear', 2, 14, 14, 2),
       ('Idea en lenguaje de señas que representa el invitar a pensar', 2, 15, 15, 2),
       ('Idea en lenguaje de señas que representa el vamonos', 2, 16, 16, 2),
       ('Idea en lenguaje de señas que representa el invitar a ver', 2, 17, 17, 2),
       ('Idea en lenguaje de señas que representa el hacer la tarea', 6, 18, 18, 2),
       ('Idea en lenguaje de señas que representa el dar un aviso', 6, 19, 19, 2),
       ('Idea en lenguaje de señas que representa el peligro', 6, 20, 20, 2),
       #
       ('Idea en español que representa los buenos días', 1, 1, 1, 1),
       ('Idea en español que representa las buenas tardes', 1, 2, 2, 1),
       ('Idea en español que representa  las buenas noches', 1, 3, 3, 1),
       ('Idea en español que representa un gusto en conocerte', 3, 4, 4, 1),
       ('Idea en español que representa  el espero nos llevemos bien', 3, 5, 5, 1),
       ('Idea en español que representa  el ser amigos', 5, 6, 6, 1),
       ('Idea en español que representa  que el clima está bonito', 6, 7, 7, 1),
       ('Idea en español que representa  el invitar', 2, 8, 8, 1),
       ('Idea en español que representa  la despedida de nos vemos', 4, 9, 9, 1),
       ('Idea en español que representa la despedida hasta luego', 4, 10, 10, 1),
       ('Idea en español que representa el preguntar cómo se siente', 5, 11, 11, 1),
       ('Idea en español que representa el ver que está feliz', 5, 12, 12, 1),
       ('Idea en español que representa  el ver animado', 3, 13, 13, 1),
       ('Idea en español que representa el invitar a pasear', 2, 14, 14, 1),
       ('Idea en español que representa el invitar a pensar', 2, 15, 15, 1),
       ('Idea en español que representa el vamonos', 2, 16, 16, 1),
       ('Idea en español que representa el invitar a ver', 2, 17, 17, 1),
       ('Idea en español que representa el hacer la tarea', 6, 18, 18, 1),
       ('Idea en español que representa el dar un aviso', 6, 19, 19, 1),
       ('Idea en español que representa el peligro', 6, 20, 20, 1);


INSERT INTO Signlator.traducciones(descripcion, lenguajes_id)
VALUES ('Traduccion en lenguaje de señas que representa los buenos días', 2),
       ('Traduccion en lenguaje de señas que representa las buenas tardes', 2),
       ('Traduccion en lenguaje de señas que representa las buenas noches', 2),
       ('Traduccion en lenguaje de señas que representa un gusto en conocerte', 2),
       ('Traduccion en lenguaje de señas que representa el espero nos llevemos bien', 2),
       ('Traduccion en lenguaje de señas que representa el ser amigos', 2),
       ('Traduccion en lenguaje de señas que representa que el clima está bonito', 2),
       ('Traduccion en lenguaje de señas que representa el invitar', 2),
       ('Traduccion en lenguaje de señas que representa la despedida de nos vemos', 2),
       ('Traduccion en lenguaje de señas que representa la despedida hasta luego', 2),
       ('Traduccion en lenguaje de señas que representa el preguntar cómo se siente', 2),
       ('Traduccion en lenguaje de señas que representa el ver que está feliz', 2),
       ('Traduccion en lenguaje de señas que representa el ver animado', 2),
       ('Traduccion en lenguaje de señas que representa el invitar a pasear', 2),
       ('Traduccion en lenguaje de señas que representa el invitar a pensar', 2),
       ('Traduccion en lenguaje de señas que representa el vamonos', 2),
       ('Traduccion en lenguaje de señas que representa el invitar a ver', 2),
       ('Traduccion en lenguaje de señas que representa el hacer la tarea', 2),
       ('Traduccion en lenguaje de señas que representa el dar un aviso', 2),
       ('Traduccion en lenguaje de señas que representa el peligro', 2),
       #
       ('Traduccion en español que representa los buenos días', 1),
       ('Traduccion en español que representa las buenas tardes', 1),
       ('Traduccion en español que representa  las buenas noches', 1),
       ('Traduccion en español que representa un gusto en conocerte', 1),
       ('Traduccion en español que representa  el espero nos llevemos bien', 1),
       ('Traduccion en español que representa  el ser amigos', 1),
       ('Traduccion en español que representa  que el clima está bonito', 1),
       ('Traduccion en español que representa  el invitar', 1),
       ('Traduccion en español que representa  la despedida de nos vemos', 1),
       ('Traduccion en español que representa la despedida hasta luego', 1),
       ('Traduccion en español que representa el preguntar cómo se siente', 1),
       ('Traduccion en español que representa el ver que está feliz', 1),
       ('Traduccion en español que representa  el ver animado', 1),
       ('Traduccion en español que representa el invitar a pasear', 1),
       ('Traduccion en español que representa el invitar a pensar', 1),
       ('Traduccion en español que representa el vamonos', 1),
       ('Traduccion en español que representa el invitar a ver', 1),
       ('Traduccion en español que representa el hacer la tarea', 1),
       ('Traduccion en español que representa el dar un aviso', 1),
       ('Traduccion en español que representa el peligro', 1);

INSERT INTO Signlator.mensajes(formato)
VALUES ('Mensaje de texto'),
       ('Mensaje en audio');

INSERT INTO Signlator.traduccionesxusuarios(usuarios_id, traducciones_id, fecha_traduccion, mensajes_id)
VALUES (1, 1, date_add(current_date, interval -10 day), 1),
       (2, 2, date_add(current_date, interval -30 day), 2),
       (3, 3, date_add(current_date, interval -50 day), 2),
       (4, 4, date_add(current_date, interval -11 day), 2),
       (5, 5, date_add(current_date, interval -1 day), 2),
       (6, 6, date_add(current_date, interval 0 day), 1),
       (7, 7, date_add(current_date, interval -50 day), 2),
       (8, 8, date_add(current_date, interval -15 day), 2),
       (9, 8, date_add(current_date, interval -21 day), 2),
       (10, 10, date_add(current_date, interval -22 day), 2),
       (11, 11, date_add(current_date, interval -25 day), 2),
       (12, 12, date_add(current_date, interval -24 day), 2),
       (13, 13, date_add(current_date, interval -29 day), 2),
       (14, 14, date_add(current_date, interval -14 day), 1),
       (15, 15, date_add(current_date, interval -13 day), 1),
       (16, 16, date_add(current_date, interval -05 day), 1),
       (17, 17, date_add(current_date, interval -08 day), 1),
       (18, 18, date_add(current_date, interval -01 day), 1),
       (19, 19, date_add(current_date, interval -02 day), 1),
       (20, 20, date_add(current_date, interval -01 day), 1),
       (1, 5, date_add(current_date, interval -02 day), 1),
       (2, 6, date_add(current_date, interval -03 day), 1),
       (3, 2, date_add(current_date, interval -02 day), 1),
       (4, 8, date_add(current_date, interval -02 day), 1),
       (5, 11, date_add(current_date, interval -04 day), 1),
       (6, 14, date_add(current_date, interval -05 day), 1),
       (7, 5, date_add(current_date, interval -40 day), 1),
       (8, 6, date_add(current_date, interval -50 day), 1),
       (9, 9, date_add(current_date, interval -80 day), 2),
       (10, 1, date_add(current_date, interval -45 day), 2),
       (11, 3, date_add(current_date, interval -19 day), 2),
       (12, 3, date_add(current_date, interval -25 day), 2),
       (13, 4, date_add(current_date, interval -27 day), 2),
       (14, 4, date_add(current_date, interval -26 day), 2),
       (15, 5, date_add(current_date, interval -15 day), 2),
       (16, 2, date_add(current_date, interval -14 day), 2),
       (17, 1, date_add(current_date, interval -13 day), 1),
       (18, 3, date_add(current_date, interval -05 day), 1),
       (19, 15, date_add(current_date, interval -35 day), 1),
       (20, 16, date_add(current_date, interval -32 day), 1),
       (1, 18, date_add(current_date, interval -17 day), 1),
       (2, 5, date_add(current_date, interval -18 day), 1),
       (3, 7, date_add(current_date, interval -21 day), 1),
       (4, 13, date_add(current_date, interval -08 day), 2),
       (5, 9, date_add(current_date, interval -07 day), 2),
       (6, 4, date_add(current_date, interval -40 day), 2),
       (7, 3, date_add(current_date, interval -62 day), 2),
       (8, 5, date_add(current_date, interval -63 day), 2),
       (9, 5, date_add(current_date, interval -84 day), 2),
       (10, 6, date_add(current_date, interval -41 day), 1),
       (11, 6, date_add(current_date, interval -14 day), 1),
       (12, 9, date_add(current_date, interval -13 day), 1),
       (13, 17, date_add(current_date, interval -05 day), 1),
       (14, 17, date_add(current_date, interval -01 day), 1),
       (15, 18, date_add(current_date, interval -02 day), 2),
       (16, 19, date_add(current_date, interval -05 day), 2),
       (17, 20, date_add(current_date, interval -07 day), 2),
       (18, 20, date_add(current_date, interval -09 day), 2),
       (19, 13, date_add(current_date, interval -11 day), 2),
       (20, 11, date_add(current_date, interval -0 day), 1);


INSERT INTO Signlator.cursosxusuarios(usuarios_id, cursos_id, progreso, fecha_inscripcion, fecha_finalizacion, estado)
VALUES (1, 1, 100, date_add(current_date, interval -23 day), date_add(current_date, interval -1 day), 'Finalizado'),
       (2, 1, 35, date_add(current_date, interval -50 day), null, 'En progreso'),
       (3, 2, 70, date_add(current_date, interval -20 day), null, 'En progreso'),
       (4, 2, 100, date_add(current_date, interval -35 day), date_add(current_date, interval -5 day), 'Finalizado'),
       (5, 3, 35, date_add(current_date, interval -35 day), null, 'En progreso'),
       (6, 3, 36, date_add(current_date, interval -36 day), null, 'En progreso'),
       (7, 4, 100, date_add(current_date, interval -50 day), date_add(current_date, interval -25 day), 'Finalizado'),
       (8, 4, 28, date_add(current_date, interval -21 day), null, 'En progreso'),
       (9, 5, 45, date_add(current_date, interval -29 day), null, 'En progreso'),
       (10, 5, 100, date_add(current_date, interval -60 day), date_add(current_date, interval -18 day), 'Finalizado'),
       (11, 6, 15, date_add(current_date, interval -62 day), null, 'En progreso'),
       (12, 6, 16, date_add(current_date, interval -15 day), null, 'En progreso'),
       (13, 7, 78, date_add(current_date, interval -14 day), null, 'En progreso'),
       (14, 7, 95, date_add(current_date, interval -85 day), null, 'En progreso'),
       (15, 8, 15, date_add(current_date, interval -15 day), null, 'En progreso'),
       (16, 8, 14, date_add(current_date, interval -24 day), null, 'En progreso'),
       (17, 9, 05, date_add(current_date, interval -23 day), null, 'En progreso'),
       (18, 9, 01, date_add(current_date, interval -29 day), null, 'En progreso'),
       (19, 7, 26, date_add(current_date, interval -30 day), null, 'En progreso'),
       (20, 8, 35, date_add(current_date, interval -15 day), null, 'En progreso'),
       #
       (1, 4, 75, date_add(current_date, interval -23 day), null, 'En progreso'),
       (2, 3, 35, date_add(current_date, interval -40 day), null, 'En progreso'),
       (3, 6, 70, date_add(current_date, interval -30 day), null, 'En progreso'),
       (4, 5, 100, date_add(current_date, interval -25 day), date_add(current_date, interval -5 day), 'Finalizado'),
       (5, 6, 35, date_add(current_date, interval -25 day), null, 'En progreso'),
       (6, 6, 36, date_add(current_date, interval -35 day), null, 'En progreso'),
       (7, 6, 100, date_add(current_date, interval -25 day), date_add(current_date, interval -25 day), 'Finalizado'),
       (8, 6, 28, date_add(current_date, interval -24 day), null, 'En progreso'),
       (9, 7, 45, date_add(current_date, interval -25 day), null, 'En progreso'),
       (10, 7, 100, date_add(current_date, interval -26 day), date_add(current_date, interval -18 day), 'Finalizado'),
       (11, 8, 15, date_add(current_date, interval -62 day), null, 'En progreso'),
       (12, 8, 16, date_add(current_date, interval -15 day), null, 'En progreso'),
       (13, 9, 78, date_add(current_date, interval -14 day), null, 'En progreso'),
       (14, 9, 95, date_add(current_date, interval -15 day), null, 'En progreso'),
       (15, 2, 15, date_add(current_date, interval -15 day), null, 'En progreso'),
       (16, 1, 14, date_add(current_date, interval -54 day), date_add(current_date, interval -38 day), 'Finalizado'),
       (17, 2, 05, date_add(current_date, interval -23 day), null, 'En progreso'),
       (18, 1, 01, date_add(current_date, interval -29 day), null, 'En progreso'),
       (19, 4, 26, date_add(current_date, interval -30 day), null, 'Finalizado'),
       (20, 4, 35, date_add(current_date, interval -75 day), date_add(current_date, interval -18 day), 'Finalizado'),
       #
       (1, 5, 75, date_add(current_date, interval -5 day), null, 'En progreso'),
       (2, 5, 100, date_add(current_date, interval -10 day), date_add(current_date, interval -2 day), 'Finalizado'),
       (3, 4, 70, date_add(current_date, interval -15 day), null, 'En progreso'),
       (4, 4, 100, date_add(current_date, interval -18 day), date_add(current_date, interval -5 day), 'Finalizado'),
       (5, 2, 35, date_add(current_date, interval -5 day), null, 'En progreso'),
       (6, 2, 36, date_add(current_date, interval -25 day), null, 'En progreso'),
       (7, 1, 100, date_add(current_date, interval -55 day), date_add(current_date, interval -25 day), 'Finalizado'),
       (8, 1, 28, date_add(current_date, interval -24 day), null, 'En progreso'),
       (9, 2, 45, date_add(current_date, interval -65 day), null, 'En progreso'),
       (10, 3, 100, date_add(current_date, interval -46 day), date_add(current_date, interval -18 day), 'Finalizado'),
       (11, 3, 15, date_add(current_date, interval -62 day), null, 'En progreso'),
       (12, 4, 100, date_add(current_date, interval -15 day), date_add(current_date, interval -5 day), 'Finalizado'),
       (13, 4, 78, date_add(current_date, interval -14 day), null, 'En progreso'),
       (14, 5, 100, date_add(current_date, interval -15 day), date_add(current_date, interval -9 day), 'Finalizado'),
       (15, 5, 15, date_add(current_date, interval -15 day), null, 'En progreso'),
       (16, 6, 14, date_add(current_date, interval -54 day), date_add(current_date, interval -38 day), 'Finalizado'),
       (17, 6, 05, date_add(current_date, interval -23 day), null, 'En progreso'),
       (18, 7, 01, date_add(current_date, interval -29 day), null, 'En progreso'),
       (19, 1, 26, date_add(current_date, interval -30 day), null, 'Finalizado'),
       (20, 5, 35, date_add(current_date, interval -75 day), date_add(current_date, interval -18 day), 'Finalizado');


INSERT INTO Signlator.anunciosxcursos(cursos_id, anuncios_id, fecha_anuncio)
VALUES (1, 1, date_add(current_date, interval -10 day)),
       (2, 2, date_add(current_date, interval -8 day)),
       (3, 1, date_add(current_date, interval -01 day)),
       (4, 9, date_add(current_date, interval -2 day)),
       (5, 7, date_add(current_date, interval -3 day)),
       (6, 4, date_add(current_date, interval -14 day)),
       (7, 4, date_add(current_date, interval -15 day)),
       (8, 5, date_add(current_date, interval -16 day)),
       (9, 5, date_add(current_date, interval -18 day)),
       (1, 5, date_add(current_date, interval -19 day)),
       (3, 2, date_add(current_date, interval -20 day)),
       (4, 2, date_add(current_date, interval -30 day)),
       (5, 1, date_add(current_date, interval -14 day)),
       (6, 3, date_add(current_date, interval -15 day)),
       (7, 3, date_add(current_date, interval -16 day)),
       (8, 1, date_add(current_date, interval -8 day)),
       (9, 1, date_add(current_date, interval -7 day)),
       (1, 2, date_add(current_date, interval -6 day)),
       (3, 3, date_add(current_date, interval -3 day)),
       (4, 3, date_add(current_date, interval -4 day)),
       (5, 3, date_add(current_date, interval -8 day)),
       (6, 9, date_add(current_date, interval -2 day)),
       (7, 9, date_add(current_date, interval -1 day)),
       (8, 7, date_add(current_date, interval -3 day)),
       (9, 7, date_add(current_date, interval -4 day)),
       (1, 4, date_add(current_date, interval -1 day));
